<template>
  <div id="app">
    <div id="nav">
    </div>
    <router-view/>
  </div>
</template>
<style>
/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=13R0u0kllll6Xooe9mSsxjOGbii */

/* Feel free to copy&paste color codes to your application */

/* As hex codes */

.md-primary { color: #303D74 } /* Main Primary color */
.md-accent { color: #6B7084 }
.md-transparent { color: #4C557C }
.md-button { color: #17286B }
.color-primary-4 { color: #081A63 }

/* Generated by Paletton.com © 2002-2014 */
/* http://paletton.com */
</style>
